### ISSUE TITLE
ToDo List part Anonyme

### ISSUE THREAD

**Issue by AdaamD** [AdaamD/InterimApp#2]
- [x] Créer classe Java "Utilisateur" avec 2 constructeurs : 1 pour candidat et 1 pour employeur 
- [x] Créer BD local ( sqlit)
- [x] Créer une classe Offre
- [x] Créer un Employeur
- [x] Stocker les offres dans la BD
- [x] Afficher les offres avec détails
- [x] Filtrer les offres selon critères ( cumuler critères) et reafficher offre
- [x] Gérer le bouton d'isncription
- [ ]         Je pense que ce sera bon pour cette partie
