### ISSUE TITLE
 ToDo List part Candidat

### ISSUE THREAD

**Issue by AdaamD** [AdaamD/InterimApp#3]
- [x] Créer le menu avec redirection vers connexion et inscription
- [x] Créer les pages d’inscription et connexion
- [x] Gérer le cas mail nom prenom obligatoire à l'inscritption ( a voir pour un mdp)
- [x] Gérer cas candidat déja inscrit en BD
- [x] Candidature, l'id est pas bon
- [x] Faire la page de recherche d'offre
- [x] Logique du bouton candidater ( qu'est ce que cela va faire ? enrgistrer dans une liste d'offres canddiaté par exemple poour le canddiat) 
- [x] gérer le bouton mes offres pour gérer les offres en cour traités non traites ect ...; ( voir marquer la candiature avec boolena traiter non traiter ? )
- [x] page de filtre déroulante ( comme liste offre avec + )
- [x] dans espace employeur un bouton qui affiche mon profil
- [x] Mon proofil mise en page + changement des info en bd 
- [x] connexio + inscription abec mdp
- [x] Arranger/Mettre en page les boite de dialogue de succés/echec de connexion
- [x] mise en page page de d'inscription, bouton inscrire bizarre
- [ ] ....

**Comment by NabilDafaoui** [comment]
- [ ] connexio + inscription abec mdp 
- [ ] page de filtre déroulante ( comme liste offre avec + )
- [ ] dans espace employeur un bouton qui affiche mon profil
